### ISSUE TITLE
Solução para funcionamento do trackpad

### ISSUE THREAD

**Issue by atosfull** [Brozinga/2am_E550_hackintosh#1]
Para o correto funcionamento do trackpad basta seguir os passos:
1) Remover as seguintes Kexts [de OC > Kexts]:
 - VoodooI2C
 - VoodooI2CHID
 [deixar somente a kext "VoodooPS2Controller"]

2) Com o python atualizado para qualquer versão 3.X (recomendado), abrir o config.plist com o ProperTree e:
* Fazer um OC Clean Snapshot (caso apareça algum aviso basta clicar em Sim)
* Fazer um OC Snapshot
* Salvar o config.plist

3) Realizar a limpeza da NVRAM (recomendo fazer pela ferramenta do próprio OC, no boot [Tools: Clean NVRAM.efi])

4) Reiniciar a máquina

![Captura de Tela 2021-12-11 às 23 26 32](https://user-images.githubusercontent.com/11442368/145698053-484c43a7-1427-42c7-8311-d32a28d14559.png)

**Comment by Brozinga** [comment]
Obrigado @atosfull vou adicionar esses itens no Readme.

**Comment by Brozinga** [comment]
Adicionado ao Readme.md
